pandar_qt_front_base_link:
  x: 0.18
  y: 0.28
  z: 0.28
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
pandar_qt_back_base_link:
  x: -0.18
  y: 0.28
  z: 0.28
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
camera_base_link:
  x: 0.18
  y: 0.31
  z: 0.64
  roll: 0.000
  pitch: 0.000
  yaw: 0.000
imu_base_link:
  x: 0.0
  y: 0.0
  z: 0.56
  roll: 0.0
  pitch: 0.0
  yaw: 0.0 
