/**:
  ros__parameters:
    sensing:
      type: diagnostic_aggregator/AnalyzerGroup
      path: sensing
      analyzers:
        lidar:
          type: diagnostic_aggregator/AnalyzerGroup
          path: lidar
          analyzers:
            performance_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: performance_monitoring
              analyzers:
                visibility:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: visibility
                  contains: [": visibility_validation"]
                  timeout: 1.0

                blockage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: blockage
                  contains: [": blockage_validation"]
                  timeout: 1.0

                connection:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: connection
                  contains: [": pandar_connection"]
                  timeout: 3.0

                ptp:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: ptp
                  contains: [": pandar_ptp"]
                  timeout: 3.0

                temperature:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: temperature
                  contains: [": pandar_temperature"]
                  timeout: 3.0
                  
        imu:
          type: diagnostic_aggregator/AnalyzerGroup
          path: imu
          analyzers:
            health_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: health_monitoring
              analyzers:
                connection:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: connection
                  contains: [": imu_connection"]
                  timeout: 3.0

                antenna:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: error
                  contains: [": imu_bit_error"]
                  timeout: 3.0
