/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "front_camera"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "front_camera/camera"
      camera_info_url: "$(find-pkg-share usb_cam)/config/camera_info.yaml"
